### ISSUE TITLE
Can not save to local or session storage

### ISSUE THREAD

**Issue by gioinv** [nuxt-community/harlem-module#6] opened 2022-02-22 08:57 UTC
When I install for nuxt 3 follow the guide but I can not save to local or storage session.
When i look at the Application tab (in browser), I see the data were changed but they lost (reset) when I press F5

The code create store as follow:

`import storageExtension from '@harlem/extension-storage';

import {
    createStore
} from '@harlem/core';

const STATE = {
    firstName: '',
    lastName: ''
};

const tsss = process.server?null:storageExtension({
    type: 'local',
    prefix: 'harlem',
    sync: true,
    restore: true,
    exclude: [],
    serialiser: state => JSON.stringify(state),
    parser: value => JSON.parse(value)
})

export const {
    state,
    getter,
    mutation
   
} = createStore('example', STATE, {
    extensions: [
       tsss
    ]
});

export const fullName = getter('fullName', state => {
    return `${state.firstName} ${state.lastName}`
})

export const setFirstName = mutation<string>('setFirstName', (state, payload) => {
    state.firstName = payload
})

export const setLastName = mutation<string>('setLastName', (state, payload) => {
    state.lastName = payload
})`

**Comment by andrewcourtice** [comment] 2022-02-26 02:20
Hi @gioinv 

I think I know what the cause of this is. It's a timing issue with Harlem itself, not necessarily the Nuxt module. Fixing it now.

Thanks 👍

**Comment by andrewcourtice** [comment] 2022-02-27 03:08
Fixed in v2.3.0 👍 Nuxt 3 demo available here: https://github.com/andrewcourtice/harlem/tree/main/examples/nuxt

**Closed** 2022-02-27 08:50 UTC
